#!/usr/bin/env python3
"""Generate .tex table fragments from paper/experiments/results.jsonl.

Writes (all \\input'd by sections/main.tex):
  paper/figures/tab01_matcher_levels.tex   - fuzzy matcher cascade hit rate
  paper/figures/tab04_dataset_card.tex     - dataset composition card
  paper/figures/tab05_main_results.tex     - main results: trick top-1, D-score MAE
  paper/figures/tab07_scorecards.tex       - (appendix) per-run scorecards

Run:
    ./venv/bin/python paper/scripts/make_tables.py
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "paper" / "experiments" / "results.jsonl"
GT_CSV = REPO / "paper" / "experiments" / "ground_truth.csv"
FIG_JSON = REPO / "data" / "fig_tricks_2025.json"
OUT_DIR = REPO / "paper" / "figures"


def load_results() -> list[dict]:
    if not RESULTS.exists():
        return []
    out = []
    for line in RESULTS.read_text().splitlines():
        line = line.strip()
        if line:
            out.append(json.loads(line))
    return out


def pct(n: int, d: int) -> str:
    return f"{100.0 * n / d:.1f}" if d else "--"


# --------------------------------------------------------------------------- #
# Table 1 --- fuzzy matcher cascade hit rate
# --------------------------------------------------------------------------- #

def table_matcher_levels(rows: list[dict]) -> str:
    level_counter: Counter[str] = Counter()
    total = 0
    for r in rows:
        if r.get("error"):
            continue
        if not r.get("parsed_trick"):
            continue
        total += 1
        match = r.get("fig_match")
        if match is None:
            level_counter["unmatched"] += 1
        else:
            level_counter[match["level"]] += 1

    order = ["exact", "alias", "normalized", "token_overlap", "physics", "unmatched"]
    pretty = {
        "exact": "L1 exact",
        "alias": "L2 alias",
        "normalized": "L3 normalised",
        "token_overlap": "L4 Jaccard",
        "physics": "L5 physics",
        "unmatched": "unmatched",
    }
    confidences = {
        "exact": "1.00",
        "alias": "1.00",
        "normalized": "0.85--0.90",
        "token_overlap": "$\\geq$0.50",
        "physics": "0.50--0.70",
        "unmatched": "---",
    }

    lines = [
        "% Auto-generated by paper/scripts/make_tables.py; do not edit.",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Level & Hit rate & Match confidence \\\\",
        "\\midrule",
    ]
    for k in order:
        n = level_counter.get(k, 0)
        lines.append(f"{pretty[k]:<16s} & {pct(n, total)}\\% & {confidences[k]} \\\\")
    lines += [
        "\\midrule",
        f"\\textbf{{total}}   & {total} calls & --- \\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Table 4 --- dataset card (static, not from results.jsonl)
# --------------------------------------------------------------------------- #

def table_dataset_card() -> str:
    # Count POOL rows from ground_truth.csv
    import csv
    pools: dict[str, dict] = defaultdict(lambda: {"rows": 0, "tricks": Counter()})
    with GT_CSV.open() as f:
        for r in csv.DictReader(f):
            p = r["pool"]
            name = r["fig_name"].strip()
            if not name:
                continue
            pools[p]["rows"] += 1
            if p == "POOL-A":
                for n in [x.strip() for x in name.split(",") if x.strip()]:
                    pools[p]["tricks"][n] += 1
            else:
                pools[p]["tricks"][name] += 1

    a_rows = pools["POOL-A"]["rows"]
    a_tricks = sum(pools["POOL-A"]["tricks"].values())
    a_distinct = len(pools["POOL-A"]["tricks"])
    b_rows = pools["POOL-B"]["rows"]
    b_distinct = len(pools["POOL-B"]["tricks"])

    lines = [
        "% Auto-generated by paper/scripts/make_tables.py; do not edit.",
        "\\begin{tabular}{llrrl}",
        "\\toprule",
        "Pool & Content & Clips & Distinct tricks & Source \\\\",
        "\\midrule",
        f"POOL-A & Full competition runs & {a_rows} & {a_distinct} "
        f"($\\approx${a_tricks} total tricks) & smartphone + GoPro \\\\",
        f"POOL-B & Single-trick segments & {b_rows} & {b_distinct} "
        f"& tutorial + competition \\\\",
        "\\midrule",
        "FIG 2025 & Official Table of Tricks & 149 & 149 "
        "& gymnastics.sport \\cite{fig2025codepoints} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Table 5 --- main results
# --------------------------------------------------------------------------- #

def _model_label(m: str) -> str:
    mapping = {
        "gemini/gemini-2.5-pro":       "Gemini 2.5 Pro (native video)",
        "gemini/gemini-2.5-flash":     "Gemini 2.5 Flash (native video)",
        "claude-cli-strip":            "Claude Sonnet 4.5 (8-frame strip)",
        "claude-cli-frames":           "Claude Sonnet 4.5 (8 frames)",
        "claude-cli":                  "Claude Sonnet 4.5 (frames, legacy)",
        "openrouter/qwen/qwen2.5-vl-72b-instruct": "Qwen2.5-VL 72B (8 frames)",
        "openrouter/google/gemini-2.5-pro":        "Gemini 2.5 Pro (via OR)",
        "openrouter/moonshotai/kimi-k2.5":         "Kimi K2.5",
        "clip-vit-b32":                "CLIP ViT-B/32 (baseline)",
    }
    return mapping.get(m, m)


def table_main_results(rows: list[dict]) -> str:
    by_model: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_model[r["model"]].append(r)

    def acc_and_dmae(recs: list[dict]) -> tuple[int, int, int, float, int]:
        """Return (correct_top1, correct_family, total, d_mae, n_errors)."""
        n = 0
        c_top1 = 0
        c_fam = 0
        d_err: list[float] = []
        n_err = 0
        for r in recs:
            if r.get("error"):
                n_err += 1
                n += 1
                continue
            n += 1
            gt_name = r["ground_truth"]["fig_name"]
            gt_d = float(r["ground_truth"].get("d_score") or 0)
            fm = r.get("fig_match") or {}
            pred_name = fm.get("name") or r.get("parsed_trick") or ""
            pred_d = float(fm.get("d_score") or 0)
            if pred_name.lower() == gt_name.lower():
                c_top1 += 1
                c_fam += 1
            else:
                # family match: same first keyword (rough)
                gt_key = gt_name.split()[0].lower()
                pr_key = pred_name.split()[0].lower() if pred_name else ""
                if gt_key and gt_key == pr_key:
                    c_fam += 1
            d_err.append(abs(gt_d - pred_d))
        d_mae = sum(d_err) / len(d_err) if d_err else 0.0
        return c_top1, c_fam, n, d_mae, n_err

    lines = [
        "% Auto-generated by paper/scripts/make_tables.py; do not edit.",
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "Model & Trick top-1 & Family acc & D-score MAE & Mean latency & Errors \\\\",
        "\\midrule",
    ]
    model_order = [
        "gemini/gemini-2.5-pro",
        "gemini/gemini-2.5-flash",
        "claude-cli-strip",
        "claude-cli-frames",
        "openrouter/qwen/qwen2.5-vl-72b-instruct",
        "openrouter/moonshotai/kimi-k2.5",
        "clip-vit-b32",
    ]
    seen = set(model_order)
    for m in list(by_model.keys()):
        if m not in seen:
            model_order.append(m)

    for m in model_order:
        recs = by_model.get(m, [])
        if not recs:
            continue
        c1, cf, n, dmae, ne = acc_and_dmae(recs)
        latency = sum(r.get("latency_s", 0) for r in recs) / max(n, 1)
        label = _model_label(m)
        lines.append(
            f"{label:<28s} & {pct(c1, n)}\\% & {pct(cf, n)}\\% & {dmae:.2f} "
            f"& {latency:.1f}\\,s & {ne} \\\\"
        )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main() -> None:
    rows = load_results()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    (OUT_DIR / "tab01_matcher_levels.tex").write_text(table_matcher_levels(rows))
    (OUT_DIR / "tab04_dataset_card.tex").write_text(table_dataset_card())
    (OUT_DIR / "tab05_main_results.tex").write_text(table_main_results(rows))

    print(f"Wrote tables from {len(rows)} result records:")
    print("  tab01_matcher_levels.tex")
    print("  tab04_dataset_card.tex")
    print("  tab05_main_results.tex")


if __name__ == "__main__":
    main()
